# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc37ee332804543504dd6937f6fdfef0509088f4c70d92259c4beabccb5953b78faded1ef94bd7a9c98302c21b1c8fa90499e0af12cd99ff4970aef1e53d55c4

test:
  secret_key_base: 2793fd5ed3048eafc772269e1a6772ffcae0571da29eff914162a86ec36f29209551fe9353ce4fda5a999a06d8a4aaf961b64574c93eb7d3ccc37e9fea25f00e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
